from __future__ import annotations

from typing import Any


SCHEMA_SPEC: dict[str, Any] = {
    "tables": [
        {
            "id": "projects",
            "primary_key": "project_id",
            "description": "Minimal project metadata for OpenSCAD-driven inventory workflows.",
            "columns": [
                {"id": "project_id", "label": "Project ID", "type": "Text"},
                {"id": "name", "label": "Name", "type": "Text"},
                {"id": "status", "label": "Status", "type": "Text"},
                {"id": "notes", "label": "Notes", "type": "Text"},
            ],
        },
        {
            "id": "cut_list",
            "primary_key": "cut_id",
            "description": "Generated from OpenSCAD/code. Treat all fields as read-only except the editable completed flag.",
            "columns": [
                {"id": "cut_id", "label": "Cut ID", "type": "Text"},
                {"id": "project_id", "label": "Project ID", "type": "Text"},
                {"id": "category", "label": "Category", "type": "Text"},
                {"id": "material_type", "label": "Material Type", "type": "Text"},
                {"id": "section_key", "label": "Section Key", "type": "Text"},
                {"id": "length_mm", "label": "Length (mm)", "type": "Numeric"},
                {"id": "width_mm", "label": "Width (mm)", "type": "Numeric"},
                {"id": "thickness_mm", "label": "Thickness (mm)", "type": "Numeric"},
                {"id": "qty_required", "label": "Qty Required", "type": "Int"},
                {"id": "unit", "label": "Unit", "type": "Text"},
                {"id": "source_kind", "label": "Source Kind", "type": "Text"},
                {"id": "source_ref", "label": "Source Ref", "type": "Text"},
                {"id": "phase", "label": "Phase", "type": "Text"},
                {"id": "completed", "label": "Completed", "type": "Bool"},
                {"id": "notes", "label": "Notes", "type": "Text"},
            ],
        },
        {
            "id": "inventory",
            "primary_key": "inventory_id",
            "description": "Human-maintained stock buckets. Pull this data back into repo snapshots after editing.",
            "columns": [
                {"id": "inventory_id", "label": "Inventory ID", "type": "Text"},
                {"id": "category", "label": "Category", "type": "Text"},
                {"id": "material_type", "label": "Material Type", "type": "Text"},
                {"id": "section_key", "label": "Section Key", "type": "Text"},
                {"id": "length_mm", "label": "Length (mm)", "type": "Numeric"},
                {"id": "width_mm", "label": "Width (mm)", "type": "Numeric"},
                {"id": "thickness_mm", "label": "Thickness (mm)", "type": "Numeric"},
                {"id": "qty_on_hand", "label": "Qty On Hand", "type": "Int"},
                {"id": "unit", "label": "Unit", "type": "Text"},
                {"id": "location", "label": "Location", "type": "Text"},
                {"id": "condition", "label": "Condition", "type": "Text"},
                {"id": "status", "label": "Status", "type": "Text"},
                {"id": "supplier", "label": "Supplier", "type": "Text"},
                {"id": "notes", "label": "Notes", "type": "Text"},
            ],
        },
        {
            "id": "shopping_list",
            "primary_key": "shopping_id",
            "description": "Agent-owned shopping table. This repo does not generate or sync shopping rows.",
            "columns": [
                {"id": "shopping_id", "label": "Shopping ID", "type": "Text"},
                {"id": "cut_key", "label": "Cut Key", "type": "Text"},
                {"id": "category", "label": "Category", "type": "Text"},
                {"id": "material_type", "label": "Material Type", "type": "Text"},
                {"id": "section_key", "label": "Section Key", "type": "Text"},
                {"id": "length_mm", "label": "Length (mm)", "type": "Numeric"},
                {"id": "width_mm", "label": "Width (mm)", "type": "Numeric"},
                {"id": "thickness_mm", "label": "Thickness (mm)", "type": "Numeric"},
                {"id": "qty_required", "label": "Qty Required", "type": "Int"},
                {"id": "qty_available", "label": "Qty Available", "type": "Int"},
                {"id": "qty_needed", "label": "Qty Needed", "type": "Int"},
                {"id": "unit", "label": "Unit", "type": "Text"},
                {"id": "purchase_unit", "label": "Purchase Unit", "type": "Text"},
                {"id": "supplier", "label": "Supplier", "type": "Text"},
                {"id": "status", "label": "Status", "type": "Text"},
                {"id": "notes", "label": "Notes", "type": "Text"},
            ],
        },
        {
            "id": "material_rules",
            "primary_key": "rule_id",
            "description": "Optional purchasing hints such as stock lengths, waste factors, and preferred suppliers.",
            "columns": [
                {"id": "rule_id", "label": "Rule ID", "type": "Text"},
                {"id": "category", "label": "Category", "type": "Text"},
                {"id": "material_type", "label": "Material Type", "type": "Text"},
                {"id": "section_key", "label": "Section Key", "type": "Text"},
                {"id": "purchase_unit", "label": "Purchase Unit", "type": "Text"},
                {"id": "stock_length_mm", "label": "Stock Length (mm)", "type": "Numeric"},
                {"id": "stock_width_mm", "label": "Stock Width (mm)", "type": "Numeric"},
                {"id": "stock_thickness_mm", "label": "Stock Thickness (mm)", "type": "Numeric"},
                {"id": "units_per_purchase", "label": "Units Per Purchase", "type": "Numeric"},
                {"id": "waste_factor", "label": "Waste Factor", "type": "Numeric"},
                {"id": "supplier", "label": "Supplier", "type": "Text"},
                {"id": "notes", "label": "Notes", "type": "Text"},
            ],
        },
    ],
}
